version: "3"

services:
    client:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./data:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
