version: "3"

services:
    client:
        image: nginx:latest
        ports:
           - "8083:80"
        volumes:
            - data:/usr/share/nginx/html
            - conf/nginx.conf:/etc/nginx/nginx.conf
