version: "3"

services:
    client:
        image: nginx:latest
        ports:
           - "8083:80"
        volumes:
            - data:/usr/share/nginx/html
            - type: bind
              source: ./conf/nginx.conf
              target: /etc/nginx/nginx.conf
